<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Ethereum\DataType;

/**
 * Ethereum data type SHHPost.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/ethjs-schema.json.
 */
class SHHPost extends EthDataType {

	/**
	 * Value for 'topics'.
	 */
	public $topics;

	/**
	 * Value for 'payload'.
	 */
	public $payload;

	/**
	 * Value for 'priority'.
	 */
	public $priority;

	/**
	 * Value for 'ttl'.
	 */
	public $ttl;

	/**
	 * Value for 'from'.
	 */
	public $from;

	/**
	 * Value for 'to'.
	 */
	public $to;

	/**
	 * @param array $topics Array of EthD
	 * @param EthD $payload
	 * @param EthQ $priority
	 * @param EthQ $ttl
	 * @param EthD $from
	 * @param EthD $to
	 */
	public function __construct(array $topics, EthD $payload, EthQ $priority, EthQ $ttl, EthD $from = null, EthD $to = null) {
		$this->topics = $topics;  
		$this->payload = $payload;  
		$this->priority = $priority;  
		$this->ttl = $ttl;  
		$this->from = $from;  
		$this->to = $to;
	}

	/**
	 * Returns a name => type array.
	 */
	public static function getTypeArray() {
		return array( 
			'topics' => '[EthD]',
			'payload' => 'EthD',
			'priority' => 'EthQ',
			'ttl' => 'EthQ',
			'from' => 'EthD',
			'to' => 'EthD',
		);
	}

	/**
	 * Returns array with values.
	 */
	public function toArray() {
		$return = [];
		(!is_null($this->topics)) ? $return['topics'] = Ethereum::valueArray($this->topics, 'EthD') : array(); 
		(!is_null($this->payload)) ? $return['payload'] = $this->payload->hexVal() : NULL; 
		(!is_null($this->priority)) ? $return['priority'] = $this->priority->hexVal() : NULL; 
		(!is_null($this->ttl)) ? $return['ttl'] = $this->ttl->hexVal() : NULL; 
		(!is_null($this->from)) ? $return['from'] = $this->from->hexVal() : NULL; 
		(!is_null($this->to)) ? $return['to'] = $this->to->hexVal() : NULL; 
		return $return;
	}
}